improve logging

diff --git a/bin/mailsync b/bin/mailsync
--- a/bin/mailsync
+++ b/bin/mailsync
@@ -1,36 +1,42 @@
 #!/usr/bin/env sh
 # Sync mail and give notification if there is new mail.
 
+logfile="$XDG_CONFIG_HOME"/mutt/.mbsync.log
+logfile_old="$logfile"_old
+
+[ -z "$logfile_old" ] && rm "$logfile_old"
+cp -f "$logfile" "$logfile_old"
+date >"$logfile"
+
 export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
 export DISPLAY=:0.0
 [ -d "$XDG_DATA_HOME/gopass" ] && export PASSWORD_STORE_DIR="$XDG_DATA_HOME/gopass"
 
+command -v notify-send >/dev/null || echo "Note that \`libnotify\` or \`libnotify-send\` should be installed for pop-up mail notifications with this script." &
+
+lognotify() {
+    echo "$1"
+    notify-send "$1"
+}
+
 # Run only if user logged in (prevent cron errors)
-pgrep -u "$USER" >/dev/null || { notify-send "$USER not logged in; sync will not run."; exit ;}
+pgrep -u "$USER" >/dev/null || { lognotify "$USER not logged in; sync will not run."; exit ;}
 # Run only if not already running in other instance
-pgrep -x mbsync >/dev/null && { notify-send "mbsync is already running."; exit ;}
+pgrep -x mbsync >/dev/null && { lognotify "mbsync is already running."; exit ;}
 
 # Checks for internet connection and set notification script.
-ping -q -c 1 1.1.1.1 > /dev/null || { notify-send "No internet connection detected."; exit ;}
-command -v notify-send >/dev/null || notify-send "Note that \`libnotify\` or \`libnotify-send\` should be installed for pop-up mail notifications with this script." &
+ping -q -c 1 1.1.1.1 > /dev/null || { lognotify "No internet connection detected."; exit ;}
 
 echo "GPG Authentication..."
 gopass find mutt | head -n 1 | xargs gopass >/dev/null 2>&1
 if [ $? -ne 0 ]; then
-    notify-send "Authentication failed!" &
+    lognotify "Authentication failed!" &
     exit 1
 fi
 
-logfile="$XDG_CONFIG_HOME"/mutt/.mbsync.log
-logfile_old="$XDG_CONFIG_HOME"/mutt/.mbsync.log_old
 
-clear
-[ -z "$logfile_old" ] && rm "$logfile_old"
-mv "$logfile" "$logfile_old"
-touch "$logfile"
-
-notify() { notify-send "mutt-wizard" "📬 $2 new mail(s) in \`$1\` account." ;}
+notify() { lognotify "mutt-wizard" "📬 $2 new mail(s) in \`$1\` account." ;}
 
 # Check account for new mail. Notify if there is new content.
 syncandnotify() {
@@ -44,7 +50,7 @@ syncandnotify() {
             # Extract subject and sender from mail.
             from=$(awk '/^From: / && ++n ==1,/^\<.*\>:/' "$file" | perl -CS -MEncode -ne 'print decode("MIME-Header", $_)' | awk '{ $1=""; if (NF>=3)$NF=""; print $0 }' | sed 's/^[[:blank:]]*[\"'\''\<]*//;s/[\"'\''\>]*[[:blank:]]*$//')
             subject=$(awk '/^Subject: / && ++n == 1,/^\<.*\>: / && ++i == 2' "$file" | head -n-1 | perl -CS -MEncode -ne 'print decode("MIME-Header", $_)' | sed 's/^Subject: //' | sed 's/^{[[:blank:]]*[\"'\''\<]*//;s/[\"'\''\>]*[[:blank:]]*$//' | tr -d '\n')
-            notify-send "📧$from:" "$subject" &
+            lognotify "📧$from:" "$subject" &
         done
     fi
 }
@@ -74,4 +80,4 @@ notmuch new 2>/dev/null
 #Create a touch file that indicates the time of the last run of mailsync
 touch "$XDG_CONFIG_HOME/mutt/.mailsynclastrun"
 
-notify-send "finished syncing"
+lognotify "finished syncing"
