exit if auth fails

diff --git a/bin/mailsync b/bin/mailsync
--- a/bin/mailsync
+++ b/bin/mailsync
@@ -10,6 +10,11 @@ command -v notify-send >/dev/null || echo "Note that \`libnotify\` or \`libnotif
 
 echo "GPG Authentication..."
 gopass find mutt | head -n 1 | xargs gopass &>/dev/null
+if [ $? -ne 0 ]; then
+    echo "Authentication failed!"
+    exit 1
+fi
+
 export DISPLAY=:0.0
 
 logfile="$XDG_CONFIG_HOME"/mutt/.mbsync.log
